dist: trusty

language: node_js
node_js:
  - 'node'

services:
  - postgresql

addons:
  postgresql: '10'

branches:
  only:
    - master

before_script:
  - psql -c 'create database mugengo_test;' -U postgres
  - cp .env.ci .env

script:
  - npm run ci

after_success:
  - cat coverage/lcov.info | coveralls
