dist: trusty

language: node_js
node_js:
  - 'node'

services:
  - postgresql

addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433

branches:
  only:
    - master

before_script:
  - psql -c 'create database mugengo_test;' -U postgres
  - cp .env.ci .env

script:
  - npm run ci

after_success:
  - cat coverage/lcov.info | coveralls
