dist: trusty

language: node_js
node_js:
  - 'node'

services:
  - postgresql

branches:
  only:
    - master

before_script:
  - psql -c 'create database mugengo_test;' -U postgres
  - cp .env.ci .env

script:
  - npm run lint
  - npm run test
  - npm run test:e2e
