dist: trusty
sudo: true

language: node_js
node_js:
  - 'node'

services:
  - postgresql

addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

branches:
  only:
    - master

before_script:
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/10/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf
  - sudo service postgresql restart
  - psql -c 'create database mugengo_test;' -U postgres
  - cp .env.ci .env

script:
  - npm run ci

after_success:
  - cat coverage/lcov.info | coveralls
